[package]
name = "atlas-vpn"
version = "1.0.0-beta.2"
edition = "2021"

[lib]
name = "atlas"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-autostart = "2"
tauri-plugin-single-instance = "2"
tauri-plugin-updater = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
reqwest = { version = "0.12", default-features = false, features = ["blocking", "json", "rustls-tls"] }
uuid = { version = "1", features = ["v4", "serde"] }
base64 = "0.22"
url = "2"
ipnet = "2"
keyring = { version = "3", features = ["windows-native"] }
rusqlite = { version = "0.32", features = ["bundled"] }
sha2 = "0.10"
maxminddb = "0.32.0"
rfd = "0.17.2"
png = "0.18.1"
regex = "1.13.1"

[target.'cfg(windows)'.dependencies]
winreg = "0.55"
windows-sys = { version = "0.59", features = ["Win32_Networking_WinInet", "Win32_Foundation", "Win32_System_JobObjects", "Win32_System_Threading", "Win32_Security", "Win32_Security_Authorization", "Win32_System_Pipes", "Win32_System_IO", "Win32_System_Rpc", "Win32_Storage_FileSystem", "Win32_UI_Shell", "Win32_UI_WindowsAndMessaging", "Win32_System_Com", "Win32_NetworkManagement_WindowsFilteringPlatform", "Win32_NetworkManagement_IpHelper", "Win32_NetworkManagement_Ndis", "Win32_Networking_WinSock", "Win32_System_Diagnostics_ToolHelp", "Win32_Graphics_Gdi"] }
